# Pandas Practical Test (30 Marks)

Dataset: NetFlix.csv

Time: 1 Hour

Maximum Marks: 30

Name:

College-Id:

Q1. Load the dataset and display the first 10 records.

In [1]:
import pandas as pd
df = pd.read_csv("Netflix.csv")
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...
5,s1002,Movie,Blue Ruin,Jeremy Saulnier,"Macon Blair, Devin Ratray, Amy Hargreaves, Kev...","United States, France",25-Feb-19,2013,R,90,"Independent Movies, Thrillers",Bad news from the past unhinges vagabond Dwigh...
6,s1003,Movie,Blue Streak,Les Mayfield,"Martin Lawrence, Luke Wilson, Peter Greene, Da...","Germany, United States",1-Jan-21,1999,PG-13,94,"Action & Adventure, Comedies",A jewel thief returns to his hiding place afte...
7,s1004,Movie,Blue Valentine,Derek Cianfrance,"Ryan Gosling, Michelle Williams, Faith Wladyka...",United States,5-Jul-18,2010,R,112,"Dramas, Independent Movies, Romantic Movies",As Cindy and Dean muddle through their languis...
8,s1005,Movie,BluffMaster!,Rohan Sippy,"Abhishek Bachchan, Priyanka Chopra, Riteish De...",India,8-Jan-21,2005,TV-14,129,"Comedies, International Movies, Romantic Movies",When his girlfriend learns the truth about his...
9,s1006,Movie,Blurred Lines: Inside the Art World,Barry Avrich,NaN,Canada,31-Dec-17,2017,TV-MA,85,Documentaries,Artists and industry insiders shed light on th...

Q2. Find:

a) Number of rows and columns

b) Data types of all columns

In [5]:
df.shape

# df.dtypes

(7787, 12)

Q3. Display the names of all columns in the dataset.

In [6]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'genres', 'description'],
      dtype='object')

Q4. Find the number of missing values present in each column.

In [7]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

Q5. How many Movies and TV Shows are available in the dataset?

In [ ]:
(df["type"] == 'Movie').count()

(df["type"] == 'TV Show').count()

np.int64(7787)

Q6. Display all titles released after 2020.

In [ ]:
titles_after_2020 = df[df['release_year'] > 2020]['title']
print(titles_after_2020)

250                                       Carmen Sandiego
319                                              Charming
397     Chris Rock Total Blackout: The Tamborine Exten...
492                                             Cobra Kai
574               Crack: Cocaine, Corruption & Conspiracy
589                           Creating The Queen's Gambit
869                                        Disenchantment
962                                   Dream Home Makeover
1477                                    Gabby's Dollhouse
1860                        Headspace Guide to Meditation
1937                                                Hilda
1950                               History of Swear Words
2245                  Inside the World’s Toughest Prisons
3138                                                Lupin
3431                   Mighty Little Bheem: Kite Festival
3528                                              Monarca
3769                                    Nailed It! Mexico
3855          Night Stalker: The Hunt for a Serial Killer
4125                                     Outside the Wire
4407                                  Pretend It’s a City
4562    Ratones Paranoicos: The Band that Rocked Argen...
5401                                          Stuck Apart
5470                                      Surviving Death
6087                                 The Idhun Chronicles
6302                         The Minimalists: Less Is Now
6337                               The Netflix Afterparty
6914                        Tribhanga - Tedhi Medhi Crazy
7281                            What Happened to Mr. Cha?
7301                          What Would Sophia Loren Do?
7384                                             Wish You
7767                                         Bling Empire
Name: title, dtype: object

Q7. Find the 10 oldest titles in the dataset based on release_year.

In [21]:
df.sort_values("release_year").head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
4298,s4868,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,30-Dec-18,1925,TV-14,1,TV Shows,This collection restores films from women who ...
4402,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,31-Mar-17,1942,TV-14,52,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
5688,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,31-Mar-17,1942,TV-14,18,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7423,s7680,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,31-Mar-17,1943,TV-PG,45,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
7353,s7617,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,31-Mar-17,1943,TV-PG,82,Documentaries,This installment of Frank Capra's acclaimed do...
7049,s7343,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,31-Mar-17,1943,TV-PG,61,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
6335,s6700,Movie,The Negro Soldier,Stuart Heisler,NaN,United States,31-Mar-17,1944,TV-14,40,"Classic Movies, Documentaries",This documentary urged African Americans to en...
6287,s6658,Movie,The Memphis Belle: A Story of a\nFlying Fortress,William Wyler,NaN,United States,31-Mar-17,1944,TV-PG,40,"Classic Movies, Documentaries",This documentary centers on the crew of the B-...
6966,s7269,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom",31-Mar-17,1944,TV-14,76,"Classic Movies, Documentaries",British and American troops join forces to lib...
3820,s4437,Movie,Nazi Concentration Camps,George Stevens,NaN,United States,31-Mar-17,1945,TV-MA,59,"Classic Movies, Documentaries",Shocking footage shows Nazi concentration camp...

Q8. Find all content having rating "PG-13" and display their titles.

In [28]:
df[df['rating'] == "PG-13"]['title']

6                           Blue Streak
13                             3 Idiots
85                        Brain on Fire
121     Bring It On: Worldwide Showdown
155                               Bully
                     ...
7752                          Blackfish
7754                     3 Days to Kill
7755                           Blackway
7776                      3 Generations
7785                       Blue Jasmine
Name: title, Length: 386, dtype: object

Q9. Count the number of titles available in each rating category.

In [30]:

df['rating'].value_counts()

rating
TV-MA       2863
TV-14       1931
TV-PG        806
R            665
PG-13        386
TV-Y         280
TV-Y7        271
PG           247
TV-G         194
NR            84
G             39
TV-Y7-FV       6
UR             5
NC-17          3
Name: count, dtype: int64

Q10. Find the average duration of all Movies and TV Shows separately.

In [35]:
movie_avg = df[df['type'] == 'Movie']['duration'].mean()
print(movie_avg)

TV_avg = df[df['type'] == 'TV Show']['duration'].mean()
print(TV_avg)

99.30797842663195
1.7759336099585061

Q11. Find the director who has directed the maximum number of titles.

In [40]:
df["director"].value_counts().head(1)

director
Raúl Campos, Jan Suter    18
Name: count, dtype: int64

Q12. Find the release year that contains the maximum number of titles.

Q13. Display all titles whose genre contains the word "Drama".

Q14. Find the top 5 most common genres.

In [41]:
df["genres"].value_counts().head(5)

genres
Documentaries                                       334
Stand-Up Comedy                                     321
Dramas, International Movies                        320
Comedies, Dramas, International Movies              243
Dramas, Independent Movies, International Movies    215
Name: count, dtype: int64

Q15. Export all Movies released after 2018 to a new CSV file named recent_movies.csv.